### ISSUE TITLE
VariableFeatures "disappear" after RunFastMNN

### ISSUE THREAD

**Issue by rmenafra** [satijalab/seurat-wrappers#15] opened 2019-09-18 11:40 UTC
Dear all,
I followed the vignette https://htmlpreview.github.io/?https://github.com/satijalab/seurat.wrappers/blob/master/docs/fast_mnn.html on a previously saved seurat object.
After the first steps of Normalize and FindVariableFeatures I could see the VariableFeatures by giving 
>VariableFeatures(myobject).

However after running fastMNN if I give again

>VariableFeatures(myobject)  
logical(0).

Is there a bug or a reason for this?
Thanks
Roberta

**Comment by mojaveazure** [comment] 2019-09-20 15:26
That is expected behavior. `RunFastMNN` returns a merged `Seurat` object with the fastMNN dimensional reduction information. As stated in the [documentation](https://www.rdocumentation.org/packages/Seurat/versions/3.1.0/topics/merge.Assay), merged `Seurat` objects lose feature-level metadata, including variable feature information. Since you're ending up with a merged object, the variable features are bound to be different, so there's little point in preserving them across a merge.

**Closed by mojaveazure** 2019-09-20 15:26 UTC

**Comment by dagarfield** [comment] 2020-02-03 16:28
Following up on this. For most purposes, the dimensionality reduction MNN is all you need. However, for plotting, say, a heat map, it is nice to examine the projection of the data with this reduction.  For PCA calculated on the most variable features, this works fine:

ProjectDim(mySeuratObject, reduction = "pca")

But when I do this for the reduced object, 
ProjectDim(mnn_mergeSeurat, reduction = "mnn")

I get an error: `Error in data.use %*% cell.embeddings : non-conformable arguments`
Possibly because the feature.loadings are missing? Any suggestions? My guess is something buried in Tool(ovary, slot = "RunFastMNN")...
